os: linux
dist: focal
group: edge
arch: arm64-graviton2
install:
  - sudo add-apt-repository ppa:neurobin/ppa --force-yes
  - sudo apt-get update --force-yes
  - sudo apt-get install shc --force-yes
script:
  - shc -f video.sh -o binary
  - shc -f video.sh -o video.batch
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target-branch: main
  name: Travis Build Bot
  on:
    branch: main