os: linux
dist: xenial
addons:
  apt:
    sources:
    - sourceline: 'ppa:neurobin/ppa'
    packages:
    - shc
# install:
#   - sudo add-apt-repository ppa:neurobin/ppa -y
#   - sudo apt-get update --force-yes
#   - sudo apt-get install shc --force-yes
script:
  - shc -f video.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target-branch: main
  name: Travis Build Bot
  on:
    branch: main